name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'

jobs:
  build-and-push-docker:
    uses: your-username/my-workflows/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ${{ vars.DOCKERHUB_USERNAME }}/my-app
      image-tag: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
      dockerfile-path: './Dockerfile'
      build-context: '.'
      platforms: 'linux/amd64,linux/arm64'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
